/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Diseno.BordeRedondo;
import Diseno.RoundedCornerButtonUI;
import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.BorderFactory;

/**
 *
 * @author javier
 */
public class Principal extends javax.swing.JFrame {

          /**
           * Creates new form Principal
           */
          public Principal() {
                    initComponents();
                    //FORMA REDONDA
                    Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 35, 35);
                    AWTUtilities.setWindowShape(this, forma);
                    //TERMINA FORMA REDONDA
                    this.setLocationRelativeTo(null);
                    initComponents2();
          }

          /**
           * This method is called from within the constructor to initialize the
           * form. WARNING: Do NOT modify this code. The content of this method
           * is always regenerated by the Form Editor.
           */
          @SuppressWarnings("unchecked")
          // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
          private void initComponents() {

                    jPanel3 = new javax.swing.JPanel();
                    jPanel2 = new javax.swing.JPanel();
                    jButton1 = new javax.swing.JButton();
                    jLabel2 = new javax.swing.JLabel();
                    jButton2 = new javax.swing.JButton();
                    jPanel1 = new javax.swing.JPanel();
                    jLabel1 = new javax.swing.JLabel();
                    jButton3 = new javax.swing.JButton();

                    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                    setUndecorated(true);

                    jPanel3.setBackground(new java.awt.Color(153, 153, 153));
                    jPanel3.setLayout(null);

                    jPanel2.setBackground(new java.awt.Color(255, 255, 255));
                    jPanel2.setLayout(null);

                    jButton1.setBackground(new java.awt.Color(0, 210, 214));
                    jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                    jButton1.setForeground(new java.awt.Color(255, 255, 255));
                    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-shopping-cart-50.png"))); // NOI18N
                    jButton1.setText("Registrar");
                    jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    jButton1.setBorderPainted(false);
                    jButton1.setFocusPainted(false);
                    jPanel2.add(jButton1);
                    jButton1.setBounds(550, 20, 240, 60);

                    jLabel2.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
                    jLabel2.setText("Chino Shop");
                    jPanel2.add(jLabel2);
                    jLabel2.setBounds(10, 10, 210, 70);

                    jButton2.setBackground(new java.awt.Color(0, 210, 214));
                    jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                    jButton2.setForeground(new java.awt.Color(255, 255, 255));
                    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-shopping-cart-50.png"))); // NOI18N
                    jButton2.setText("Registrar");
                    jButton2.setBorder(null);
                    jButton2.setBorderPainted(false);
                    jButton2.setFocusPainted(false);
                    jPanel2.add(jButton2);
                    jButton2.setBounds(270, 20, 240, 60);

                    jPanel3.add(jPanel2);
                    jPanel2.setBounds(0, 0, 1400, 100);

                    jPanel1.setBackground(new java.awt.Color(247, 247, 247));
                    jPanel1.setFocusable(false);
                    jPanel1.setLayout(null);

                    jLabel1.setBackground(new java.awt.Color(0, 0, 0));
                    jLabel1.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
                    jLabel1.setText("Hola, Hello");
                    jPanel1.add(jLabel1);
                    jLabel1.setBounds(120, 70, 320, 120);

                    jButton3.setBackground(new java.awt.Color(255, 255, 0));
                    jButton3.setText("jButton3");
                    jPanel1.add(jButton3);
                    jButton3.setBounds(650, 280, 280, 170);

                    jPanel3.add(jPanel1);
                    jPanel1.setBounds(0, 100, 1400, 800);

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                    );
                    layout.setVerticalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                    );

                    pack();
          }// </editor-fold>//GEN-END:initComponents

          /**
           * @param args the command line arguments
           */
          public static void main(String args[]) {
                    /* Set the Nimbus look and feel */
                    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                     */
                    try {
                              for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                        if ("Dracula".equals(info.getName())) {
                                                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                                  break;
                                        }
                              }
                    } catch (ClassNotFoundException ex) {
                              java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                              java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                              java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                              java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                    //</editor-fold>

                    /* Create and display the form */
                    java.awt.EventQueue.invokeLater(new Runnable() {
                              public void run() {
                                        new Principal().setVisible(true);
                              }
                    });
          }
          
          public void initComponents2(){
                    //jButton1.setBorder(new BordeRedondo(70));
                    //jButton1.setBorder(BorderFactory.createEmptyBorder(0,0,0,0)); // Especially important 
                    jButton1.setUI(new RoundedCornerButtonUI());
                    jButton1.setFocusable(false);
                    jButton1.setBorder(BorderFactory.createEmptyBorder(0,0,0,0)); // Especially important
                    jButton3.setUI(new RoundedCornerButtonUI());
                    jButton3.setFocusable(false);
                    jButton3.setBorder(BorderFactory.createEmptyBorder(0,0,0,0)); // Especially important
                    //jButton3.setContentAreaFilled(false);
          }

          // Variables declaration - do not modify//GEN-BEGIN:variables
          private javax.swing.JButton jButton1;
          private javax.swing.JButton jButton2;
          private javax.swing.JButton jButton3;
          private javax.swing.JLabel jLabel1;
          private javax.swing.JLabel jLabel2;
          private javax.swing.JPanel jPanel1;
          private javax.swing.JPanel jPanel2;
          private javax.swing.JPanel jPanel3;
          // End of variables declaration//GEN-END:variables
}
