/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Diseno.RoundedCornerButtonUI;
import Diseno.RoundedPanel;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Font;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javier
 */
public class Productos extends javax.swing.JFrame {

          private int EstadoARealizar = 0;
          
          static Principal FramePrincipal = new Principal();
          Color RojoCerrar = new Color(245, 73, 73);
          Color AzulAtras = new Color(25, 35, 84);
          String titulos[] = {"ID", "NOMBRE", "MARCA", "CANTIDAD", "TIPO", "DISPONIBLE"};
          DefaultTableModel modelo = new DefaultTableModel(null, titulos) {
                    @Override
                    public boolean isCellEditable(int fila, int columna) {
                              if (columna == 6) {
                                        return true;
                              } else {
                                        return false;
                              }
                    }
          };
          
          /**
           * Creates new form Productos
           */
          public Productos() {
                    initComponents();
                    Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 35, 35);
                    AWTUtilities.setWindowShape(this, forma);
                    this.setLocationRelativeTo(null);
                    initComponents2();
          }

          /**
           * This method is called from within the constructor to initialize the
           * form. WARNING: Do NOT modify this code. The content of this method
           * is always regenerated by the Form Editor.
           */
          @SuppressWarnings("unchecked")
          // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
          private void initComponents() {

                    jPanel1 = new javax.swing.JPanel();
                    Btt_Cerrar = new javax.swing.JButton();
                    Btt_Atras = new javax.swing.JButton();
                    Panel_Interno = new RoundedPanel(50);
                    Btt_Nuevo = new javax.swing.JButton();
                    Btt_Modificar = new javax.swing.JButton();
                    Btt_Eliminar = new javax.swing.JButton();
                    jLabel1 = new javax.swing.JLabel();
                    Txt_id = new javax.swing.JTextField();
                    jSeparator1 = new javax.swing.JSeparator();
                    jLabel2 = new javax.swing.JLabel();
                    Txt_nombre = new javax.swing.JTextField();
                    jSeparator2 = new javax.swing.JSeparator();
                    jLabel3 = new javax.swing.JLabel();
                    Txt_marca = new javax.swing.JTextField();
                    jSeparator3 = new javax.swing.JSeparator();
                    jLabel4 = new javax.swing.JLabel();
                    Txt_cantidad = new javax.swing.JTextField();
                    jSeparator4 = new javax.swing.JSeparator();
                    jLabel5 = new javax.swing.JLabel();
                    Txt_tipo = new javax.swing.JTextField();
                    jSeparator5 = new javax.swing.JSeparator();
                    jLabel6 = new javax.swing.JLabel();
                    Cbx_disponible = new javax.swing.JComboBox<>();
                    Btt_Agregar = new javax.swing.JButton();
                    jScrollPane1 = new javax.swing.JScrollPane();
                    jTable1 = new javax.swing.JTable();
                    Btt_CargarTabla = new javax.swing.JButton();
                    jLabel7 = new javax.swing.JLabel();

                    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                    setUndecorated(true);
                    setResizable(false);

                    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                    jPanel1.setLayout(null);

                    Btt_Cerrar.setBackground(new java.awt.Color(255, 255, 255));
                    Btt_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-shutdown-48.png"))); // NOI18N
                    Btt_Cerrar.setBorder(null);
                    Btt_Cerrar.setOpaque(false);
                    Btt_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_CerrarMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_CerrarMouseExited(evt);
                              }
                    });
                    Btt_Cerrar.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_CerrarActionPerformed(evt);
                              }
                    });
                    jPanel1.add(Btt_Cerrar);
                    Btt_Cerrar.setBounds(10, 10, 50, 50);

                    Btt_Atras.setBackground(new java.awt.Color(255, 255, 255));
                    Btt_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-back-48.png"))); // NOI18N
                    Btt_Atras.setBorder(null);
                    Btt_Atras.setOpaque(false);
                    Btt_Atras.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_AtrasMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_AtrasMouseExited(evt);
                              }
                    });
                    Btt_Atras.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_AtrasActionPerformed(evt);
                              }
                    });
                    jPanel1.add(Btt_Atras);
                    Btt_Atras.setBounds(70, 10, 50, 50);

                    Panel_Interno.setBackground(new java.awt.Color(74, 129, 212));
                    Panel_Interno.setForeground(new java.awt.Color(0, 0, 0));
                    Panel_Interno.setLayout(null);

                    Btt_Nuevo.setBackground(new java.awt.Color(137, 107, 235));
                    Btt_Nuevo.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
                    Btt_Nuevo.setForeground(new java.awt.Color(255, 255, 255));
                    Btt_Nuevo.setText("NUEVO");
                    Btt_Nuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    Btt_Nuevo.setBorderPainted(false);
                    Btt_Nuevo.setFocusPainted(false);
                    Btt_Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_NuevoMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_NuevoMouseExited(evt);
                              }
                    });
                    Btt_Nuevo.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_NuevoActionPerformed(evt);
                              }
                    });
                    Panel_Interno.add(Btt_Nuevo);
                    Btt_Nuevo.setBounds(50, 20, 320, 50);

                    Btt_Modificar.setBackground(new java.awt.Color(26, 43, 86));
                    Btt_Modificar.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
                    Btt_Modificar.setForeground(new java.awt.Color(255, 255, 255));
                    Btt_Modificar.setText("MODIFICAR");
                    Btt_Modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    Btt_Modificar.setBorderPainted(false);
                    Btt_Modificar.setFocusPainted(false);
                    Btt_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_ModificarMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_ModificarMouseExited(evt);
                              }
                    });
                    Btt_Modificar.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_ModificarActionPerformed(evt);
                              }
                    });
                    Panel_Interno.add(Btt_Modificar);
                    Btt_Modificar.setBounds(50, 120, 320, 50);

                    Btt_Eliminar.setBackground(new java.awt.Color(242, 135, 77));
                    Btt_Eliminar.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
                    Btt_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
                    Btt_Eliminar.setText("ELIMINAR");
                    Btt_Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    Btt_Eliminar.setBorderPainted(false);
                    Btt_Eliminar.setFocusPainted(false);
                    Btt_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_EliminarMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_EliminarMouseExited(evt);
                              }
                    });
                    Btt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_EliminarActionPerformed(evt);
                              }
                    });
                    Panel_Interno.add(Btt_Eliminar);
                    Btt_Eliminar.setBounds(50, 220, 320, 50);

                    jPanel1.add(Panel_Interno);
                    Panel_Interno.setBounds(960, 20, 420, 300);

                    jLabel1.setBackground(new java.awt.Color(24, 64, 128));
                    jLabel1.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
                    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel1.setText("ID");
                    jLabel1.setOpaque(true);
                    jPanel1.add(jLabel1);
                    jLabel1.setBounds(30, 140, 130, 30);

                    Txt_id.setBackground(new java.awt.Color(255, 255, 255));
                    Txt_id.setFont(new java.awt.Font("Lato Light", 1, 24)); // NOI18N
                    Txt_id.setForeground(new java.awt.Color(24, 64, 128));
                    Txt_id.setBorder(null);
                    Txt_id.setEnabled(false);
                    Txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
                              public void keyTyped(java.awt.event.KeyEvent evt) {
                                        Txt_idKeyTyped(evt);
                              }
                    });
                    jPanel1.add(Txt_id);
                    Txt_id.setBounds(170, 140, 400, 50);
                    jPanel1.add(jSeparator1);
                    jSeparator1.setBounds(170, 190, 400, 2);

                    jLabel2.setBackground(new java.awt.Color(24, 64, 128));
                    jLabel2.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
                    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel2.setText("NOMBRE");
                    jLabel2.setOpaque(true);
                    jPanel1.add(jLabel2);
                    jLabel2.setBounds(30, 230, 130, 30);

                    Txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
                    Txt_nombre.setFont(new java.awt.Font("Lato Light", 1, 24)); // NOI18N
                    Txt_nombre.setForeground(new java.awt.Color(24, 64, 128));
                    Txt_nombre.setBorder(null);
                    Txt_nombre.setEnabled(false);
                    jPanel1.add(Txt_nombre);
                    Txt_nombre.setBounds(170, 230, 400, 50);
                    jPanel1.add(jSeparator2);
                    jSeparator2.setBounds(170, 280, 400, 2);

                    jLabel3.setBackground(new java.awt.Color(24, 64, 128));
                    jLabel3.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
                    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel3.setText("MARCA");
                    jLabel3.setOpaque(true);
                    jPanel1.add(jLabel3);
                    jLabel3.setBounds(30, 320, 130, 30);

                    Txt_marca.setBackground(new java.awt.Color(255, 255, 255));
                    Txt_marca.setFont(new java.awt.Font("Lato Light", 1, 24)); // NOI18N
                    Txt_marca.setForeground(new java.awt.Color(24, 64, 128));
                    Txt_marca.setBorder(null);
                    Txt_marca.setEnabled(false);
                    jPanel1.add(Txt_marca);
                    Txt_marca.setBounds(170, 320, 400, 50);
                    jPanel1.add(jSeparator3);
                    jSeparator3.setBounds(170, 370, 400, 2);

                    jLabel4.setBackground(new java.awt.Color(24, 64, 128));
                    jLabel4.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
                    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel4.setText("CANTIDAD");
                    jLabel4.setOpaque(true);
                    jPanel1.add(jLabel4);
                    jLabel4.setBounds(30, 410, 130, 30);

                    Txt_cantidad.setBackground(new java.awt.Color(255, 255, 255));
                    Txt_cantidad.setFont(new java.awt.Font("Lato Light", 1, 24)); // NOI18N
                    Txt_cantidad.setForeground(new java.awt.Color(24, 64, 128));
                    Txt_cantidad.setBorder(null);
                    Txt_cantidad.setEnabled(false);
                    jPanel1.add(Txt_cantidad);
                    Txt_cantidad.setBounds(170, 410, 400, 50);
                    jPanel1.add(jSeparator4);
                    jSeparator4.setBounds(170, 460, 400, 2);

                    jLabel5.setBackground(new java.awt.Color(24, 64, 128));
                    jLabel5.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
                    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel5.setText("TIPO");
                    jLabel5.setOpaque(true);
                    jPanel1.add(jLabel5);
                    jLabel5.setBounds(30, 500, 130, 30);

                    Txt_tipo.setBackground(new java.awt.Color(255, 255, 255));
                    Txt_tipo.setFont(new java.awt.Font("Lato Light", 1, 24)); // NOI18N
                    Txt_tipo.setForeground(new java.awt.Color(24, 64, 128));
                    Txt_tipo.setBorder(null);
                    Txt_tipo.setEnabled(false);
                    Txt_tipo.addKeyListener(new java.awt.event.KeyAdapter() {
                              public void keyTyped(java.awt.event.KeyEvent evt) {
                                        Txt_tipoKeyTyped(evt);
                              }
                    });
                    jPanel1.add(Txt_tipo);
                    Txt_tipo.setBounds(170, 500, 400, 50);
                    jPanel1.add(jSeparator5);
                    jSeparator5.setBounds(170, 550, 400, 2);

                    jLabel6.setBackground(new java.awt.Color(24, 64, 128));
                    jLabel6.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
                    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel6.setText("DISPONIBLE");
                    jLabel6.setOpaque(true);
                    jPanel1.add(jLabel6);
                    jLabel6.setBounds(30, 590, 130, 30);

                    Cbx_disponible.setBackground(new java.awt.Color(255, 255, 255));
                    Cbx_disponible.setFont(new java.awt.Font("Lato Light", 1, 18)); // NOI18N
                    Cbx_disponible.setForeground(new java.awt.Color(24, 64, 128));
                    Cbx_disponible.setEnabled(false);
                    jPanel1.add(Cbx_disponible);
                    Cbx_disponible.setBounds(170, 590, 100, 50);

                    Btt_Agregar.setBackground(new java.awt.Color(255, 255, 255));
                    Btt_Agregar.setFont(new java.awt.Font("Lato", 1, 36)); // NOI18N
                    Btt_Agregar.setForeground(new java.awt.Color(205, 0, 41));
                    Btt_Agregar.setText("REALIZAR");
                    Btt_Agregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    Btt_Agregar.setBorderPainted(false);
                    Btt_Agregar.setEnabled(false);
                    Btt_Agregar.setFocusPainted(false);
                    Btt_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_AgregarMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_AgregarMouseExited(evt);
                              }
                    });
                    Btt_Agregar.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_AgregarActionPerformed(evt);
                              }
                    });
                    jPanel1.add(Btt_Agregar);
                    Btt_Agregar.setBounds(30, 700, 540, 100);

                    jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
                    jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

                    jTable1.setBackground(new java.awt.Color(255, 255, 255));
                    jTable1.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
                    jTable1.setModel(new javax.swing.table.DefaultTableModel(
                              new Object [][] {
                                        {null, null, null, null, null, null},
                                        {null, null, null, null, null, null},
                                        {null, null, null, null, null, null},
                                        {null, null, null, null, null, null}
                              },
                              new String [] {
                                        "NIT", "NOMBRE", "APELLIDO", "DIRECCION", "TELEFONO", "NACIMIENTO"
                              }
                    ) {
                              boolean[] canEdit = new boolean [] {
                                        false, false, false, false, false, false
                              };

                              public boolean isCellEditable(int rowIndex, int columnIndex) {
                                        return canEdit [columnIndex];
                              }
                    });
                    jTable1.setFocusable(false);
                    jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
                    jTable1.setRowHeight(25);
                    jTable1.setSelectionBackground(new java.awt.Color(232, 57, 95));
                    jTable1.setShowVerticalLines(false);
                    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        jTable1MouseClicked(evt);
                              }
                    });
                    jScrollPane1.setViewportView(jTable1);

                    jPanel1.add(jScrollPane1);
                    jScrollPane1.setBounds(600, 370, 780, 430);

                    Btt_CargarTabla.setBackground(new java.awt.Color(24, 4, 29));
                    Btt_CargarTabla.setFont(new java.awt.Font("Lato", 1, 36)); // NOI18N
                    Btt_CargarTabla.setForeground(new java.awt.Color(255, 255, 255));
                    Btt_CargarTabla.setText("CARGAR TABLA");
                    Btt_CargarTabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    Btt_CargarTabla.setBorderPainted(false);
                    Btt_CargarTabla.setFocusPainted(false);
                    Btt_CargarTabla.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_CargarTablaMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_CargarTablaMouseExited(evt);
                              }
                    });
                    Btt_CargarTabla.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_CargarTablaActionPerformed(evt);
                              }
                    });
                    jPanel1.add(Btt_CargarTabla);
                    Btt_CargarTabla.setBounds(600, 820, 780, 60);

                    jLabel7.setFont(new java.awt.Font("Lato", 1, 36)); // NOI18N
                    jLabel7.setForeground(new java.awt.Color(239, 87, 86));
                    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoChino.png"))); // NOI18N
                    jLabel7.setText("PRODUCTOS");
                    jPanel1.add(jLabel7);
                    jLabel7.setBounds(220, 40, 310, 70);

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                    );
                    layout.setVerticalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                    );

                    pack();
          }// </editor-fold>//GEN-END:initComponents

          private void Btt_CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_CerrarMouseEntered
                    Btt_Cerrar.setBackground(RojoCerrar);
          }//GEN-LAST:event_Btt_CerrarMouseEntered

          private void Btt_CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_CerrarMouseExited
                    Btt_Cerrar.setBackground(Color.WHITE);
          }//GEN-LAST:event_Btt_CerrarMouseExited

          private void Btt_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_CerrarActionPerformed
                    System.exit(0);
                    /*
                    FramePrincipal.md.agregar(0, 0, 1, "mamarre00");
                    FramePrincipal.md.agregar(1, 0, 2, "mamarre10");
                    FramePrincipal.md.agregar(2, 0, 3, "mamarre20");
                    FramePrincipal.md.agregar(1, 1, 4, "mamarre11");
                    FramePrincipal.md.agregar(2, 2, 5, "mamarre22");
                    FramePrincipal.md.agregar(0, 3, 6, "mamarre03");
                    FramePrincipal.md.agregar(1, 4, 7, "mamarre14");
                    FramePrincipal.md.agregar(2, 5, 8, "mamarre25");
                    FramePrincipal.md.agregar(0, 6, 9, "mamarre06");
                    FramePrincipal.md.agregar(0, 7, 10, "mamarre07");
                    FramePrincipal.md.agregar(3, 12, 11, "mamarre1211");*/
          }//GEN-LAST:event_Btt_CerrarActionPerformed

          private void Btt_AtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_AtrasMouseEntered
                    Btt_Atras.setBackground(AzulAtras);
          }//GEN-LAST:event_Btt_AtrasMouseEntered

          private void Btt_AtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_AtrasMouseExited
                    Btt_Atras.setBackground(Color.WHITE);
          }//GEN-LAST:event_Btt_AtrasMouseExited

          private void Btt_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_AtrasActionPerformed
                    FramePrincipal.setVisible(true);
                    this.dispose();

                    /*FramePrincipal.md.imprimirMatriz();
                    FramePrincipal.md.imprimirMatrizG();
                    FramePrincipal.md.GenerarDOTMatrizDispersa();
                    FramePrincipal.md.AbrirDOTMatrizDispersa();*/
          }//GEN-LAST:event_Btt_AtrasActionPerformed

          private void Btt_NuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_NuevoMouseEntered
                    Btt_Nuevo.setSize(320, 100);
          }//GEN-LAST:event_Btt_NuevoMouseEntered

          private void Btt_NuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_NuevoMouseExited
                    Btt_Nuevo.setSize(320, 50);
          }//GEN-LAST:event_Btt_NuevoMouseExited

          private void Btt_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_NuevoActionPerformed
                    EstadoARealizar = 1;
                    HabilitarComponentes(true);
          }//GEN-LAST:event_Btt_NuevoActionPerformed

          private void Btt_ModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_ModificarMouseEntered
                    Btt_Modificar.setSize(320, 100);
          }//GEN-LAST:event_Btt_ModificarMouseEntered

          private void Btt_ModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_ModificarMouseExited
                    Btt_Modificar.setSize(320, 50);
          }//GEN-LAST:event_Btt_ModificarMouseExited

          private void Btt_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_ModificarActionPerformed
                    EstadoARealizar = 2;
                    HabilitarComponentes(true);
          }//GEN-LAST:event_Btt_ModificarActionPerformed

          private void Btt_EliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_EliminarMouseEntered
                    Btt_Eliminar.setSize(320, 100);
          }//GEN-LAST:event_Btt_EliminarMouseEntered

          private void Btt_EliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_EliminarMouseExited
                    Btt_Eliminar.setSize(320, 50);
          }//GEN-LAST:event_Btt_EliminarMouseExited

          private void Btt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_EliminarActionPerformed
                    EstadoARealizar = 3;
                    HabilitarComponentes(true);
          }//GEN-LAST:event_Btt_EliminarActionPerformed

          private void Txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_idKeyTyped
                    char car = evt.getKeyChar();
                    if (Character.isLetter(car)) {
                              evt.consume();
                              getToolkit().beep();
                    } else {

                    }
          }//GEN-LAST:event_Txt_idKeyTyped

          private void Txt_tipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_tipoKeyTyped
                    char car = evt.getKeyChar();
                    if (Character.isLetter(car)) {
                              evt.consume();
                              getToolkit().beep();
                    } else {

                    }
          }//GEN-LAST:event_Txt_tipoKeyTyped

          private void Btt_AgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_AgregarMouseEntered
                    Btt_Agregar.setBackground(new Color(205, 0, 41));
                    Btt_Agregar.setForeground(Color.WHITE);
          }//GEN-LAST:event_Btt_AgregarMouseEntered

          private void Btt_AgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_AgregarMouseExited
                    Btt_Agregar.setBackground(Color.WHITE);
                    Btt_Agregar.setForeground(new Color(205, 0, 41));
          }//GEN-LAST:event_Btt_AgregarMouseExited

          private void Btt_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_AgregarActionPerformed
                    if (Txt_id.getText().equals("") || Txt_nombre.getText().equals("") || Txt_marca.getText().equals("") || Txt_cantidad.getText().equals("") || Txt_tipo.getText().equals("") || Cbx_disponible.getSelectedItem().equals("")) {
                              JOptionPane.showMessageDialog(null, "Debe completar todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                              if (EstadoARealizar == 1) {
                                        boolean disponible = false;
                                        if (Cbx_disponible.getSelectedItem().toString().equals("SI")){
                                                  disponible = true;
                                        } else {
                                                  disponible = false;
                                        }
                                        FramePrincipal.lp.agregarALista(Integer.parseInt(Txt_id.getText()), Txt_nombre.getText(), Txt_marca.getText(), Integer.parseInt(Txt_cantidad.getText()), Txt_tipo.getText(), disponible);
                                        System.out.println("En total hay: " + FramePrincipal.ldc.CuantoHay());
                                        FramePrincipal.lp.ImprimirListaDoble();
                                        JOptionPane.showMessageDialog(null, "Usuario agregado con exito!", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                                        CargarTabla();
                                        LimpiarComponentes();
                                        HabilitarComponentes(false);
                              } else if (EstadoARealizar == 2) {
                                        boolean disponible = false;
                                        if (Cbx_disponible.getSelectedItem().toString().equals("SI")){
                                                  disponible = true;
                                        } else {
                                                  disponible = false;
                                        }
                                        FramePrincipal.lp.ModificarListaProductos(Integer.parseInt(Txt_id.getText()), Txt_nombre.getText(), Txt_marca.getText(), Integer.parseInt(Txt_cantidad.getText()), Txt_tipo.getText(), disponible);
                                        JOptionPane.showMessageDialog(null, "Usuario modificado con exito!", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                                        CargarTabla();
                                        LimpiarComponentes();
                                        HabilitarComponentes(false);
                              } else if (EstadoARealizar == 3) {
                                        FramePrincipal.lp.EliminarListaProductos(Integer.parseInt(Txt_id.getText()));
                                        JOptionPane.showMessageDialog(null, "Usuario eliminado con exito!", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                                        CargarTabla();
                                        LimpiarComponentes();
                                        HabilitarComponentes(false);
                              } else {

                              }
                    }
          }//GEN-LAST:event_Btt_AgregarActionPerformed

          private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                    int fila = jTable1.getSelectedRow();
                    Txt_id.setText(jTable1.getValueAt(fila, 0).toString());
                    Txt_nombre.setText(jTable1.getValueAt(fila, 1).toString());
                    Txt_marca.setText(jTable1.getValueAt(fila, 2).toString());
                    Txt_cantidad.setText(jTable1.getValueAt(fila, 3).toString());
                    Txt_tipo.setText(jTable1.getValueAt(fila, 4).toString());
                    Cbx_disponible.setSelectedItem(jTable1.getValueAt(fila, 5));
          }//GEN-LAST:event_jTable1MouseClicked

          private void Btt_CargarTablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_CargarTablaMouseEntered
                    Btt_CargarTabla.setSize(790, 70);
                    Btt_CargarTabla.setText("CARGAR TABLA");
          }//GEN-LAST:event_Btt_CargarTablaMouseEntered

          private void Btt_CargarTablaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_CargarTablaMouseExited
                    Btt_CargarTabla.setSize(780, 60);
                    Btt_CargarTabla.setText("CARGAR TABLA");
          }//GEN-LAST:event_Btt_CargarTablaMouseExited

          private void Btt_CargarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_CargarTablaActionPerformed
                    CargarTabla();
          }//GEN-LAST:event_Btt_CargarTablaActionPerformed

          /**
           * @param args the command line arguments
           */
          public static void main(String args[]) {
                    /* Set the Nimbus look and feel */
                    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                     */
                    try {
                              for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                        if ("Nimbus".equals(info.getName())) {
                                                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                                  break;
                                        }
                              }
                    } catch (ClassNotFoundException ex) {
                              java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                              java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                              java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                              java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                    //</editor-fold>

                    /* Create and display the form */
                    java.awt.EventQueue.invokeLater(new Runnable() {
                              public void run() {
                                        new Productos().setVisible(true);
                              }
                    });
          }
          
          public void initComponents2() {
                    Btt_Cerrar.setUI(new RoundedCornerButtonUI());
                    Btt_Cerrar.setFocusable(false);
                    Btt_Cerrar.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    Btt_Atras.setUI(new RoundedCornerButtonUI());
                    Btt_Atras.setFocusable(false);
                    Btt_Atras.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    
                    Btt_Agregar.setUI(new RoundedCornerButtonUI());
                    Btt_Agregar.setFocusable(false);
                    Btt_Agregar.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    Btt_Agregar.setHorizontalTextPosition(SwingConstants.CENTER);
                    Btt_Agregar.setVerticalTextPosition(SwingConstants.BOTTOM);
                    
                    Btt_CargarTabla.setUI(new RoundedCornerButtonUI());
                    Btt_CargarTabla.setFocusable(false);
                    Btt_CargarTabla.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    Btt_CargarTabla.setHorizontalTextPosition(SwingConstants.CENTER);
                    Btt_CargarTabla.setVerticalTextPosition(SwingConstants.BOTTOM);
                    
                    Btt_Nuevo.setUI(new RoundedCornerButtonUI());
                    Btt_Nuevo.setFocusable(false);
                    Btt_Nuevo.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    Btt_Nuevo.setHorizontalTextPosition(SwingConstants.CENTER);
                    Btt_Nuevo.setVerticalTextPosition(SwingConstants.BOTTOM);
                    
                    Btt_Modificar.setUI(new RoundedCornerButtonUI());
                    Btt_Modificar.setFocusable(false);
                    Btt_Modificar.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    Btt_Modificar.setHorizontalTextPosition(SwingConstants.CENTER);
                    Btt_Modificar.setVerticalTextPosition(SwingConstants.BOTTOM);
                    
                    Btt_Eliminar.setUI(new RoundedCornerButtonUI());
                    Btt_Eliminar.setFocusable(false);
                    Btt_Eliminar.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    Btt_Eliminar.setHorizontalTextPosition(SwingConstants.CENTER);
                    Btt_Eliminar.setVerticalTextPosition(SwingConstants.BOTTOM);
                    
                    Panel_Interno.setOpaque(false);
                              
                    Cbx_disponible.addItem("SI");
                    Cbx_disponible.addItem("NO");
                    
                    jTable1.setBorder(null);
                    jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
                    jTable1.getTableHeader().setOpaque(true);
                    jTable1.getTableHeader().setBackground(new Color(32, 136, 203));
                    jTable1.getTableHeader().setForeground(new Color(255, 255, 255));
                    jTable1.setRowHeight(25);
          }
          
          private void CargarTabla() {
                    jTable1.setModel(modelo);
                    FramePrincipal.lp.AgregarAModeloTabla(modelo);
          }
          
          private void LimpiarComponentes(){
                    Txt_id.setText("");
                    Txt_nombre.setText("");
                    Txt_marca.setText("");
                    Txt_cantidad.setText("");
                    Txt_tipo.setText("");
                    Cbx_disponible.setSelectedIndex(0);
          }
          
          private void HabilitarComponentes(boolean estado){
                    Txt_id.setEnabled(estado);
                    Txt_nombre.setEnabled(estado);
                    Txt_marca.setEnabled(estado);
                    Txt_cantidad.setEnabled(estado);
                    Txt_tipo.setEnabled(estado);
                    Cbx_disponible.setEnabled(estado);
                    Btt_Agregar.setEnabled(estado);
          }

          // Variables declaration - do not modify//GEN-BEGIN:variables
          private javax.swing.JButton Btt_Agregar;
          private javax.swing.JButton Btt_Atras;
          private javax.swing.JButton Btt_CargarTabla;
          private javax.swing.JButton Btt_Cerrar;
          private javax.swing.JButton Btt_Eliminar;
          private javax.swing.JButton Btt_Modificar;
          private javax.swing.JButton Btt_Nuevo;
          private javax.swing.JComboBox<String> Cbx_disponible;
          private javax.swing.JPanel Panel_Interno;
          private javax.swing.JTextField Txt_cantidad;
          private javax.swing.JTextField Txt_id;
          private javax.swing.JTextField Txt_marca;
          private javax.swing.JTextField Txt_nombre;
          private javax.swing.JTextField Txt_tipo;
          private javax.swing.JLabel jLabel1;
          private javax.swing.JLabel jLabel2;
          private javax.swing.JLabel jLabel3;
          private javax.swing.JLabel jLabel4;
          private javax.swing.JLabel jLabel5;
          private javax.swing.JLabel jLabel6;
          private javax.swing.JLabel jLabel7;
          private javax.swing.JPanel jPanel1;
          private javax.swing.JScrollPane jScrollPane1;
          private javax.swing.JSeparator jSeparator1;
          private javax.swing.JSeparator jSeparator2;
          private javax.swing.JSeparator jSeparator3;
          private javax.swing.JSeparator jSeparator4;
          private javax.swing.JSeparator jSeparator5;
          private javax.swing.JTable jTable1;
          // End of variables declaration//GEN-END:variables
}
