/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Diseno.RoundedCornerButtonUI;
import Diseno.RoundedPanel;
import static Interfaz.Productos.FramePrincipal;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Font;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javier
 */
public class Ventas extends javax.swing.JFrame {

          
          private int EstadoARealizar = 0;
          public static int ContadorFactura = 0;
          
          static Principal FramePrincipal = new Principal();
          Color RojoCerrar = new Color(245, 73, 73);
          Color AzulAtras = new Color(25, 35, 84);
          String titulosProductos[] = {"ID", "NOMBRE", "MARCA", "CANTIDAD","PRECIO", "TIPO", "DISPONIBLE"};
          String titulosClientes[] = {"NIT", "NOMBRE", "APELLIDO", "DIRECCION", "TELEFONO", "NACIMIENTO"};
          DefaultTableModel modeloProductos = new DefaultTableModel(null, titulosProductos) {
                    @Override
                    public boolean isCellEditable(int fila, int columna) {
                              if (columna == 7) {
                                        return true;
                              } else {
                                        return false;
                              }
                    }
          };
          DefaultTableModel modeloClientes = new DefaultTableModel(null, titulosClientes) {
                    @Override
                    public boolean isCellEditable(int fila, int columna) {
                              if (columna == 6) {
                                        return true;
                              } else {
                                        return false;
                              }
                    }
          };
          /**
           * Creates new form Ventas
           */
          public Ventas() {
                    initComponents();
                    Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 35, 35);
                    AWTUtilities.setWindowShape(this, forma);
                    this.setLocationRelativeTo(null);
                    initComponents2();
          }

          /**
           * This method is called from within the constructor to initialize the
           * form. WARNING: Do NOT modify this code. The content of this method
           * is always regenerated by the Form Editor.
           */
          @SuppressWarnings("unchecked")
          // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
          private void initComponents() {

                    jPanel1 = new javax.swing.JPanel();
                    Btt_Cerrar = new javax.swing.JButton();
                    Btt_Atras = new javax.swing.JButton();
                    Panel_Interno = new RoundedPanel(50);
                    Btt_Nuevo = new javax.swing.JButton();
                    Btt_Modificar = new javax.swing.JButton();
                    Btt_Eliminar = new javax.swing.JButton();
                    jLabel1 = new javax.swing.JLabel();
                    Txt_Nit_Cliente = new javax.swing.JTextField();
                    jSeparator1 = new javax.swing.JSeparator();
                    jLabel2 = new javax.swing.JLabel();
                    Txt_Id_Producto = new javax.swing.JTextField();
                    jSeparator2 = new javax.swing.JSeparator();
                    Btt_Agregar = new javax.swing.JButton();
                    jScrollPane1 = new javax.swing.JScrollPane();
                    Table_Clientes = new javax.swing.JTable();
                    Btt_CargarTabla = new javax.swing.JButton();
                    jLabel7 = new javax.swing.JLabel();
                    jScrollPane2 = new javax.swing.JScrollPane();
                    Table_Productos = new javax.swing.JTable();
                    jLabel3 = new javax.swing.JLabel();
                    jLabel4 = new javax.swing.JLabel();

                    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                    setUndecorated(true);
                    setResizable(false);

                    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                    jPanel1.setLayout(null);

                    Btt_Cerrar.setBackground(new java.awt.Color(255, 255, 255));
                    Btt_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-shutdown-48.png"))); // NOI18N
                    Btt_Cerrar.setBorder(null);
                    Btt_Cerrar.setOpaque(false);
                    Btt_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_CerrarMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_CerrarMouseExited(evt);
                              }
                    });
                    Btt_Cerrar.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_CerrarActionPerformed(evt);
                              }
                    });
                    jPanel1.add(Btt_Cerrar);
                    Btt_Cerrar.setBounds(10, 10, 50, 50);

                    Btt_Atras.setBackground(new java.awt.Color(255, 255, 255));
                    Btt_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-back-48.png"))); // NOI18N
                    Btt_Atras.setBorder(null);
                    Btt_Atras.setOpaque(false);
                    Btt_Atras.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_AtrasMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_AtrasMouseExited(evt);
                              }
                    });
                    Btt_Atras.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_AtrasActionPerformed(evt);
                              }
                    });
                    jPanel1.add(Btt_Atras);
                    Btt_Atras.setBounds(70, 10, 50, 50);

                    Panel_Interno.setBackground(new java.awt.Color(74, 129, 212));
                    Panel_Interno.setForeground(new java.awt.Color(0, 0, 0));
                    Panel_Interno.setLayout(null);

                    Btt_Nuevo.setBackground(new java.awt.Color(137, 107, 235));
                    Btt_Nuevo.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
                    Btt_Nuevo.setForeground(new java.awt.Color(255, 255, 255));
                    Btt_Nuevo.setText("NUEVO");
                    Btt_Nuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    Btt_Nuevo.setBorderPainted(false);
                    Btt_Nuevo.setFocusPainted(false);
                    Btt_Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_NuevoMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_NuevoMouseExited(evt);
                              }
                    });
                    Btt_Nuevo.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_NuevoActionPerformed(evt);
                              }
                    });
                    Panel_Interno.add(Btt_Nuevo);
                    Btt_Nuevo.setBounds(50, 20, 320, 50);

                    Btt_Modificar.setBackground(new java.awt.Color(26, 43, 86));
                    Btt_Modificar.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
                    Btt_Modificar.setForeground(new java.awt.Color(255, 255, 255));
                    Btt_Modificar.setText("MODIFICAR");
                    Btt_Modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    Btt_Modificar.setBorderPainted(false);
                    Btt_Modificar.setFocusPainted(false);
                    Btt_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_ModificarMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_ModificarMouseExited(evt);
                              }
                    });
                    Btt_Modificar.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_ModificarActionPerformed(evt);
                              }
                    });
                    Panel_Interno.add(Btt_Modificar);
                    Btt_Modificar.setBounds(50, 120, 320, 50);

                    Btt_Eliminar.setBackground(new java.awt.Color(242, 135, 77));
                    Btt_Eliminar.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
                    Btt_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
                    Btt_Eliminar.setText("ELIMINAR");
                    Btt_Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    Btt_Eliminar.setBorderPainted(false);
                    Btt_Eliminar.setFocusPainted(false);
                    Btt_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_EliminarMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_EliminarMouseExited(evt);
                              }
                    });
                    Btt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_EliminarActionPerformed(evt);
                              }
                    });
                    Panel_Interno.add(Btt_Eliminar);
                    Btt_Eliminar.setBounds(50, 220, 320, 50);

                    jPanel1.add(Panel_Interno);
                    Panel_Interno.setBounds(960, 20, 420, 300);

                    jLabel1.setBackground(new java.awt.Color(24, 64, 128));
                    jLabel1.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
                    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel1.setText("NIT CLIENTE");
                    jLabel1.setOpaque(true);
                    jPanel1.add(jLabel1);
                    jLabel1.setBounds(30, 140, 130, 30);

                    Txt_Nit_Cliente.setBackground(new java.awt.Color(255, 255, 255));
                    Txt_Nit_Cliente.setFont(new java.awt.Font("Lato Light", 1, 24)); // NOI18N
                    Txt_Nit_Cliente.setForeground(new java.awt.Color(24, 64, 128));
                    Txt_Nit_Cliente.setBorder(null);
                    Txt_Nit_Cliente.setEnabled(false);
                    Txt_Nit_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
                              public void keyTyped(java.awt.event.KeyEvent evt) {
                                        Txt_Nit_ClienteKeyTyped(evt);
                              }
                    });
                    jPanel1.add(Txt_Nit_Cliente);
                    Txt_Nit_Cliente.setBounds(170, 140, 400, 50);
                    jPanel1.add(jSeparator1);
                    jSeparator1.setBounds(170, 190, 400, 2);

                    jLabel2.setBackground(new java.awt.Color(24, 64, 128));
                    jLabel2.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
                    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel2.setText("ID PRODUCTO");
                    jLabel2.setOpaque(true);
                    jPanel1.add(jLabel2);
                    jLabel2.setBounds(30, 230, 130, 30);

                    Txt_Id_Producto.setBackground(new java.awt.Color(255, 255, 255));
                    Txt_Id_Producto.setFont(new java.awt.Font("Lato Light", 1, 24)); // NOI18N
                    Txt_Id_Producto.setForeground(new java.awt.Color(24, 64, 128));
                    Txt_Id_Producto.setBorder(null);
                    Txt_Id_Producto.setEnabled(false);
                    jPanel1.add(Txt_Id_Producto);
                    Txt_Id_Producto.setBounds(170, 230, 400, 50);
                    jPanel1.add(jSeparator2);
                    jSeparator2.setBounds(170, 280, 400, 2);

                    Btt_Agregar.setBackground(new java.awt.Color(255, 255, 255));
                    Btt_Agregar.setFont(new java.awt.Font("Lato", 1, 36)); // NOI18N
                    Btt_Agregar.setForeground(new java.awt.Color(205, 0, 41));
                    Btt_Agregar.setText("REALIZAR");
                    Btt_Agregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    Btt_Agregar.setBorderPainted(false);
                    Btt_Agregar.setEnabled(false);
                    Btt_Agregar.setFocusPainted(false);
                    Btt_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_AgregarMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_AgregarMouseExited(evt);
                              }
                    });
                    Btt_Agregar.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_AgregarActionPerformed(evt);
                              }
                    });
                    jPanel1.add(Btt_Agregar);
                    Btt_Agregar.setBounds(620, 160, 290, 100);

                    jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
                    jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

                    Table_Clientes.setBackground(new java.awt.Color(255, 255, 255));
                    Table_Clientes.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
                    Table_Clientes.setModel(new javax.swing.table.DefaultTableModel(
                              new Object [][] {
                                        {null, null, null, null, null, null},
                                        {null, null, null, null, null, null},
                                        {null, null, null, null, null, null},
                                        {null, null, null, null, null, null}
                              },
                              new String [] {
                                        "NIT", "NOMBRE", "APELLIDO", "DIRECCION", "TELEFONO", "NACIMIENTO"
                              }
                    ) {
                              boolean[] canEdit = new boolean [] {
                                        false, false, false, false, false, false
                              };

                              public boolean isCellEditable(int rowIndex, int columnIndex) {
                                        return canEdit [columnIndex];
                              }
                    });
                    Table_Clientes.setFocusable(false);
                    Table_Clientes.setIntercellSpacing(new java.awt.Dimension(0, 0));
                    Table_Clientes.setRowHeight(25);
                    Table_Clientes.setSelectionBackground(new java.awt.Color(232, 57, 95));
                    Table_Clientes.setShowVerticalLines(false);
                    Table_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        Table_ClientesMouseClicked(evt);
                              }
                    });
                    jScrollPane1.setViewportView(Table_Clientes);

                    jPanel1.add(jScrollPane1);
                    jScrollPane1.setBounds(750, 430, 630, 400);

                    Btt_CargarTabla.setBackground(new java.awt.Color(24, 4, 29));
                    Btt_CargarTabla.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
                    Btt_CargarTabla.setForeground(new java.awt.Color(255, 255, 255));
                    Btt_CargarTabla.setText("CARGAR TABLA");
                    Btt_CargarTabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    Btt_CargarTabla.setBorderPainted(false);
                    Btt_CargarTabla.setFocusPainted(false);
                    Btt_CargarTabla.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseEntered(java.awt.event.MouseEvent evt) {
                                        Btt_CargarTablaMouseEntered(evt);
                              }
                              public void mouseExited(java.awt.event.MouseEvent evt) {
                                        Btt_CargarTablaMouseExited(evt);
                              }
                    });
                    Btt_CargarTabla.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        Btt_CargarTablaActionPerformed(evt);
                              }
                    });
                    jPanel1.add(Btt_CargarTabla);
                    Btt_CargarTabla.setBounds(310, 840, 780, 50);

                    jLabel7.setFont(new java.awt.Font("Lato", 1, 36)); // NOI18N
                    jLabel7.setForeground(new java.awt.Color(239, 87, 86));
                    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoChino.png"))); // NOI18N
                    jLabel7.setText("VENTAS");
                    jPanel1.add(jLabel7);
                    jLabel7.setBounds(220, 40, 310, 70);

                    jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
                    jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

                    Table_Productos.setBackground(new java.awt.Color(255, 255, 255));
                    Table_Productos.setFont(new java.awt.Font("Lato Light", 0, 14)); // NOI18N
                    Table_Productos.setModel(new javax.swing.table.DefaultTableModel(
                              new Object [][] {
                                        {null, null, null, null, null, null, null},
                                        {null, null, null, null, null, null, null},
                                        {null, null, null, null, null, null, null},
                                        {null, null, null, null, null, null, null}
                              },
                              new String [] {
                                        "ID", "NOMBRE", "MARCA", "CANTIDAD", "PRECIO", "TIPO", "DISPONIBLE"
                              }
                    ) {
                              boolean[] canEdit = new boolean [] {
                                        false, false, false, false, false, false, true
                              };

                              public boolean isCellEditable(int rowIndex, int columnIndex) {
                                        return canEdit [columnIndex];
                              }
                    });
                    Table_Productos.setFocusable(false);
                    Table_Productos.setIntercellSpacing(new java.awt.Dimension(0, 0));
                    Table_Productos.setRowHeight(25);
                    Table_Productos.setSelectionBackground(new java.awt.Color(232, 57, 95));
                    Table_Productos.setShowVerticalLines(false);
                    Table_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
                              public void mouseClicked(java.awt.event.MouseEvent evt) {
                                        Table_ProductosMouseClicked(evt);
                              }
                    });
                    jScrollPane2.setViewportView(Table_Productos);

                    jPanel1.add(jScrollPane2);
                    jScrollPane2.setBounds(20, 430, 630, 400);

                    jLabel3.setBackground(new java.awt.Color(0, 0, 0));
                    jLabel3.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
                    jLabel3.setForeground(new java.awt.Color(153, 153, 0));
                    jLabel3.setText("CLIENTES");
                    jPanel1.add(jLabel3);
                    jLabel3.setBounds(1020, 390, 110, 40);

                    jLabel4.setBackground(new java.awt.Color(0, 0, 0));
                    jLabel4.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
                    jLabel4.setForeground(new java.awt.Color(153, 153, 0));
                    jLabel4.setText("PRODUCTOS");
                    jPanel1.add(jLabel4);
                    jLabel4.setBounds(250, 390, 170, 40);

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                    );
                    layout.setVerticalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                    );

                    pack();
          }// </editor-fold>//GEN-END:initComponents

          private void Btt_CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_CerrarMouseEntered
                    Btt_Cerrar.setBackground(RojoCerrar);
          }//GEN-LAST:event_Btt_CerrarMouseEntered

          private void Btt_CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_CerrarMouseExited
                    Btt_Cerrar.setBackground(Color.WHITE);
          }//GEN-LAST:event_Btt_CerrarMouseExited

          private void Btt_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_CerrarActionPerformed
                    System.exit(0);
                    /*
                    FramePrincipal.md.agregar(0, 0, 1, "mamarre00");
                    FramePrincipal.md.agregar(1, 0, 2, "mamarre10");
                    FramePrincipal.md.agregar(2, 0, 3, "mamarre20");
                    FramePrincipal.md.agregar(1, 1, 4, "mamarre11");
                    FramePrincipal.md.agregar(2, 2, 5, "mamarre22");
                    FramePrincipal.md.agregar(0, 3, 6, "mamarre03");
                    FramePrincipal.md.agregar(1, 4, 7, "mamarre14");
                    FramePrincipal.md.agregar(2, 5, 8, "mamarre25");
                    FramePrincipal.md.agregar(0, 6, 9, "mamarre06");
                    FramePrincipal.md.agregar(0, 7, 10, "mamarre07");
                    FramePrincipal.md.agregar(3, 12, 11, "mamarre1211");*/
          }//GEN-LAST:event_Btt_CerrarActionPerformed

          private void Btt_AtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_AtrasMouseEntered
                    Btt_Atras.setBackground(AzulAtras);
          }//GEN-LAST:event_Btt_AtrasMouseEntered

          private void Btt_AtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_AtrasMouseExited
                    Btt_Atras.setBackground(Color.WHITE);
          }//GEN-LAST:event_Btt_AtrasMouseExited

          private void Btt_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_AtrasActionPerformed
                    FramePrincipal.setVisible(true);
                    this.dispose();

                    /*FramePrincipal.md.imprimirMatriz();
                    FramePrincipal.md.imprimirMatrizG();
                    FramePrincipal.md.GenerarDOTMatrizDispersa();
                    FramePrincipal.md.AbrirDOTMatrizDispersa();*/
          }//GEN-LAST:event_Btt_AtrasActionPerformed

          private void Btt_NuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_NuevoMouseEntered
                    Btt_Nuevo.setSize(320, 100);
          }//GEN-LAST:event_Btt_NuevoMouseEntered

          private void Btt_NuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_NuevoMouseExited
                    Btt_Nuevo.setSize(320, 50);
          }//GEN-LAST:event_Btt_NuevoMouseExited

          private void Btt_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_NuevoActionPerformed
                    EstadoARealizar = 1;
                    HabilitarComponentes(true);
          }//GEN-LAST:event_Btt_NuevoActionPerformed

          private void Btt_ModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_ModificarMouseEntered
                    Btt_Modificar.setSize(320, 100);
          }//GEN-LAST:event_Btt_ModificarMouseEntered

          private void Btt_ModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_ModificarMouseExited
                    Btt_Modificar.setSize(320, 50);
          }//GEN-LAST:event_Btt_ModificarMouseExited

          private void Btt_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_ModificarActionPerformed
                    EstadoARealizar = 2;
                    HabilitarComponentes(true);
          }//GEN-LAST:event_Btt_ModificarActionPerformed

          private void Btt_EliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_EliminarMouseEntered
                    Btt_Eliminar.setSize(320, 100);
          }//GEN-LAST:event_Btt_EliminarMouseEntered

          private void Btt_EliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_EliminarMouseExited
                    Btt_Eliminar.setSize(320, 50);
          }//GEN-LAST:event_Btt_EliminarMouseExited

          private void Btt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_EliminarActionPerformed
                    EstadoARealizar = 3;
                    HabilitarComponentes(true);
          }//GEN-LAST:event_Btt_EliminarActionPerformed

          private void Txt_Nit_ClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Nit_ClienteKeyTyped
                    char car = evt.getKeyChar();
                    if (Character.isLetter(car)) {
                              evt.consume();
                              getToolkit().beep();
                    } else {

                    }
          }//GEN-LAST:event_Txt_Nit_ClienteKeyTyped

          private void Btt_AgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_AgregarMouseEntered
                    Btt_Agregar.setBackground(new Color(205, 0, 41));
                    Btt_Agregar.setForeground(Color.WHITE);
          }//GEN-LAST:event_Btt_AgregarMouseEntered

          private void Btt_AgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_AgregarMouseExited
                    Btt_Agregar.setBackground(Color.WHITE);
                    Btt_Agregar.setForeground(new Color(205, 0, 41));
          }//GEN-LAST:event_Btt_AgregarMouseExited

          private void Btt_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_AgregarActionPerformed
                    if (Txt_Nit_Cliente.getText().equals("") || Txt_Id_Producto.getText().equals("")) {
                              JOptionPane.showMessageDialog(null, "Debe completar todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
                    } else {
                              if (EstadoARealizar == 1) {
                                        //FramePrincipal.lp.agregarALista(Integer.parseInt(Txt_id.getText()), Txt_nombre.getText(), Txt_marca.getText(), Integer.parseInt(Txt_cantidad.getText()), Txt_tipo.getText(), disponible);
                                        String ContadorString = Integer.toString(ContadorFactura);
                                        String separador[] = Txt_Id_Producto.getText().split(",");
                                        System.out.println("ESTE ES EL TAMANO DEL SEPARADOR: " + separador.length);
                                        for (int i = 0; i < separador.length; i++) {
                                                  int cantidadComprar = 0;
                                                  boolean aceptado = false;
                                                  do {
                                                            String verificar = JOptionPane.showInputDialog(this, "Ingrese la cantidad del producto [" + separador[i] + "] a comprar", 0);
                                                            try {
                                                                      cantidadComprar = Integer.parseInt(verificar);
                                                                      aceptado = true;
                                                            } catch (Exception e) {
                                                                      JOptionPane.showConfirmDialog(this, "Unicamente se permiten numeros", "Error", JOptionPane.ERROR_MESSAGE);
                                                            }
                                                  } while (!aceptado);
                                                  
                                                  //FramePrincipal.md.agregar(Integer.parseInt(Txt_Nit_Cliente.getText()), Integer.parseInt(Txt_Id_Producto.getText()), ContadorFactura, "Factura: " + ContadorString);
                                                  FramePrincipal.md.agregar(Integer.parseInt(Txt_Nit_Cliente.getText()), Integer.parseInt(separador[i]), ContadorFactura, cantidadComprar, "Factura: " + ContadorFactura);
                                        }
                                        JOptionPane.showMessageDialog(null, "Venta agregada con exito!", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                                        CargarTablas();
                                        LimpiarComponentes();
                                        HabilitarComponentes(false);
                                        ContadorFactura++;
                              } else if (EstadoARealizar == 2) {
                                        //FramePrincipal.lp.ModificarListaProductos(Integer.parseInt(Txt_id.getText()), Txt_nombre.getText(), Txt_marca.getText(), Integer.parseInt(Txt_cantidad.getText()), Txt_tipo.getText(), disponible);
                                        JOptionPane.showMessageDialog(null, "Venta modificada con exito!", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                                        CargarTablas();
                                        LimpiarComponentes();
                                        HabilitarComponentes(false);
                              } else if (EstadoARealizar == 3) {
                                        FramePrincipal.lp.EliminarListaProductos(Integer.parseInt(Txt_Nit_Cliente.getText()));
                                        JOptionPane.showMessageDialog(null, "Venta eliminada con exito!", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                                        CargarTablas();
                                        LimpiarComponentes();
                                        HabilitarComponentes(false);
                              } else {

                              }
                    }
          }//GEN-LAST:event_Btt_AgregarActionPerformed

          private void Table_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ClientesMouseClicked
                    int fila = Table_Clientes.getSelectedRow();
                    Txt_Nit_Cliente.setText(Table_Clientes.getValueAt(fila, 0).toString());
          }//GEN-LAST:event_Table_ClientesMouseClicked

          private void Btt_CargarTablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_CargarTablaMouseEntered
                    Btt_CargarTabla.setSize(790, 70);
                    Btt_CargarTabla.setText("CARGAR TABLA");
          }//GEN-LAST:event_Btt_CargarTablaMouseEntered

          private void Btt_CargarTablaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btt_CargarTablaMouseExited
                    Btt_CargarTabla.setSize(780, 60);
                    Btt_CargarTabla.setText("CARGAR TABLA");
          }//GEN-LAST:event_Btt_CargarTablaMouseExited

          private void Btt_CargarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_CargarTablaActionPerformed
                    CargarTablas();
          }//GEN-LAST:event_Btt_CargarTablaActionPerformed

          private void Table_ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ProductosMouseClicked
                    int fila[] = Table_Productos.getSelectedRows();
                    String listado = "";
                    for (int i = 0; i < fila.length; i++) {
                              if (i == fila.length) {
                                        listado +=  Table_Productos.getValueAt(i, 0);
                              } else {
                                        listado +=  Table_Productos.getValueAt(i, 0) + ",";
                              }
                    }
                    Txt_Id_Producto.setText(listado);
                    /*Txt_Id_Producto.setText(Table_Productos.getValueAt(fila, 0).toString());
                    //System.out.println(Table_Productos.getValueAt(fila, 4).toString());
                    int cuantosExistencia = Integer.parseInt(Table_Productos.getValueAt(fila, 4).toString());
                    for (int i = 1; i <= cuantosExistencia; i++) {
                              System.out.println("iteracion " + i);
                              Cbx_Cantidad.addItem(Integer.toString(i));
                    }*/
                    listado = "";
          }//GEN-LAST:event_Table_ProductosMouseClicked

          /**
           * @param args the command line arguments
           */
          public static void main(String args[]) {
                    /* Set the Nimbus look and feel */
                    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                     */
                    try {
                              for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                        if ("Nimbus".equals(info.getName())) {
                                                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                                  break;
                                        }
                              }
                    } catch (ClassNotFoundException ex) {
                              java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                              java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                              java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                              java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                    //</editor-fold>

                    /* Create and display the form */
                    java.awt.EventQueue.invokeLater(new Runnable() {
                              public void run() {
                                        new Ventas().setVisible(true);
                              }
                    });
          }
          
          public void initComponents2() {
                    Btt_Cerrar.setUI(new RoundedCornerButtonUI());
                    Btt_Cerrar.setFocusable(false);
                    Btt_Cerrar.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    Btt_Atras.setUI(new RoundedCornerButtonUI());
                    Btt_Atras.setFocusable(false);
                    Btt_Atras.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    
                    Btt_Agregar.setUI(new RoundedCornerButtonUI());
                    Btt_Agregar.setFocusable(false);
                    Btt_Agregar.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    Btt_Agregar.setHorizontalTextPosition(SwingConstants.CENTER);
                    Btt_Agregar.setVerticalTextPosition(SwingConstants.BOTTOM);
                    
                    Btt_CargarTabla.setUI(new RoundedCornerButtonUI());
                    Btt_CargarTabla.setFocusable(false);
                    Btt_CargarTabla.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    Btt_CargarTabla.setHorizontalTextPosition(SwingConstants.CENTER);
                    Btt_CargarTabla.setVerticalTextPosition(SwingConstants.BOTTOM);
                    
                    Btt_Nuevo.setUI(new RoundedCornerButtonUI());
                    Btt_Nuevo.setFocusable(false);
                    Btt_Nuevo.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    Btt_Nuevo.setHorizontalTextPosition(SwingConstants.CENTER);
                    Btt_Nuevo.setVerticalTextPosition(SwingConstants.BOTTOM);
                    
                    Btt_Modificar.setUI(new RoundedCornerButtonUI());
                    Btt_Modificar.setFocusable(false);
                    Btt_Modificar.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    Btt_Modificar.setHorizontalTextPosition(SwingConstants.CENTER);
                    Btt_Modificar.setVerticalTextPosition(SwingConstants.BOTTOM);
                    
                    Btt_Eliminar.setUI(new RoundedCornerButtonUI());
                    Btt_Eliminar.setFocusable(false);
                    Btt_Eliminar.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
                    Btt_Eliminar.setHorizontalTextPosition(SwingConstants.CENTER);
                    Btt_Eliminar.setVerticalTextPosition(SwingConstants.BOTTOM);
                    
                    Panel_Interno.setOpaque(false);
                    
                    Table_Clientes.setBorder(null);
                    Table_Clientes.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
                    Table_Clientes.getTableHeader().setOpaque(true);
                    Table_Clientes.getTableHeader().setBackground(new Color(32, 136, 203));
                    Table_Clientes.getTableHeader().setForeground(new Color(255, 255, 255));
                    Table_Clientes.setRowHeight(25);
                    
                    Table_Productos.setBorder(null);
                    Table_Productos.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
                    Table_Productos.getTableHeader().setOpaque(true);
                    Table_Productos.getTableHeader().setBackground(new Color(32, 136, 203));
                    Table_Productos.getTableHeader().setForeground(new Color(255, 255, 255));
                    Table_Productos.setRowHeight(25);
          }
          
          private void CargarTablas() {
                    Table_Clientes.setModel(modeloClientes);
                    Table_Productos.setModel(modeloProductos);
                    FramePrincipal.lp.AgregarAModeloTabla(modeloProductos);
                    FramePrincipal.ldc.AgregarAModeloTabla(modeloClientes);
          }
          
          private void LimpiarComponentes(){
                    Txt_Nit_Cliente.setText("");
                    Txt_Id_Producto.setText("");
          }
          
          private void HabilitarComponentes(boolean estado){
                    Txt_Nit_Cliente.setEnabled(estado);
                    Txt_Id_Producto.setEnabled(estado);
                    Btt_Agregar.setEnabled(estado);
          }

          // Variables declaration - do not modify//GEN-BEGIN:variables
          private javax.swing.JButton Btt_Agregar;
          private javax.swing.JButton Btt_Atras;
          private javax.swing.JButton Btt_CargarTabla;
          private javax.swing.JButton Btt_Cerrar;
          private javax.swing.JButton Btt_Eliminar;
          private javax.swing.JButton Btt_Modificar;
          private javax.swing.JButton Btt_Nuevo;
          private javax.swing.JPanel Panel_Interno;
          private javax.swing.JTable Table_Clientes;
          private javax.swing.JTable Table_Productos;
          private javax.swing.JTextField Txt_Id_Producto;
          private javax.swing.JTextField Txt_Nit_Cliente;
          private javax.swing.JLabel jLabel1;
          private javax.swing.JLabel jLabel2;
          private javax.swing.JLabel jLabel3;
          private javax.swing.JLabel jLabel4;
          private javax.swing.JLabel jLabel7;
          private javax.swing.JPanel jPanel1;
          private javax.swing.JScrollPane jScrollPane1;
          private javax.swing.JScrollPane jScrollPane2;
          private javax.swing.JSeparator jSeparator1;
          private javax.swing.JSeparator jSeparator2;
          // End of variables declaration//GEN-END:variables
}
